// <auto-generated />
using System;
using InventoryPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryPro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260530023549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryPro.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 101L);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantityInStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ReorderLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Supplier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProductID");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_Quantity", "[QuantityInStock] >= 0");

                            t.HasCheckConstraint("CK_Products_ReorderLevel", "[ReorderLevel] >= 0");

                            t.HasCheckConstraint("CK_Products_UnitPrice", "[UnitPrice] > 0");
                        });

                    b.HasData(
                        new
                        {
                            ProductID = 101,
                            Description = "White A4 printing paper, 80gsm",
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "A4 Paper (500 sheets)",
                            QuantityInStock = 150,
                            ReorderLevel = 20,
                            Supplier = "PaperWorld Durban",
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            ProductID = 102,
                            Description = "Blue ballpoint pens, medium tip",
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "Ballpoint Pens (Box of 10)",
                            QuantityInStock = 8,
                            ReorderLevel = 10,
                            Supplier = "Stationery Hub",
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            ProductID = 103,
                            Description = "Steel 4-drawer filing cabinet, grey",
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "Filing Cabinet (4-drawer)",
                            QuantityInStock = 3,
                            ReorderLevel = 5,
                            Supplier = "Office Essentials SA",
                            UnitPrice = 850.00m
                        },
                        new
                        {
                            ProductID = 104,
                            Description = "Heavy-duty stapler with staples",
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "Stapler",
                            QuantityInStock = 25,
                            ReorderLevel = 8,
                            Supplier = "Stationery Hub",
                            UnitPrice = 55.00m
                        },
                        new
                        {
                            ProductID = 105,
                            Description = "Assorted colours: red, blue, green, black",
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductName = "Whiteboard Markers (Set of 4)",
                            QuantityInStock = 4,
                            ReorderLevel = 10,
                            Supplier = "PaperWorld Durban",
                            UnitPrice = 35.00m
                        });
                });

            modelBuilder.Entity("InventoryPro.Models.Sale", b =>
                {
                    b.Property<int>("SaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleID"), 1001L);

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SaleID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("Sales", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sales_QuantitySold", "[QuantitySold] > 0");

                            t.HasCheckConstraint("CK_Sales_TotalPrice", "[TotalPrice] > 0");
                        });

                    b.HasData(
                        new
                        {
                            SaleID = 1001,
                            ProductID = 101,
                            QuantitySold = 5,
                            SaleDate = new DateTime(2025, 1, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 225.00m,
                            UserID = 2
                        },
                        new
                        {
                            SaleID = 1002,
                            ProductID = 102,
                            QuantitySold = 3,
                            SaleDate = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 75.00m,
                            UserID = 2
                        },
                        new
                        {
                            SaleID = 1003,
                            ProductID = 103,
                            QuantitySold = 1,
                            SaleDate = new DateTime(2025, 1, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 850.00m,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("InventoryPro.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lefa Mokoena",
                            PasswordHash = "$2a$11$IAkvyWAKZwhhW5qGbX3IGuHZ9STPzYqvBC94Cb1ACbE8saz8BQXmu",
                            Role = "Manager",
                            Username = "lefa_m"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kago Khumalo",
                            PasswordHash = "$2a$11$vaowO8s7XhKTHyyksKd2t.sBDUcQGzsVPIIjbnRLWth93OwfObf6C",
                            Role = "Shop Assistant",
                            Username = "kago_k"
                        });
                });

            modelBuilder.Entity("InventoryPro.Models.Sale", b =>
                {
                    b.HasOne("InventoryPro.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryPro.Models.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryPro.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("InventoryPro.Models.User", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
